# render.yaml — Civic Internet v1
services:
  - type: web
    name: gic-gateway
    env: node
    rootDir: services/gic_gateway_service
    buildCommand: npm ci
    startCommand: npm run start
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: RPC_URL
        value: # e.g. https://sepolia.infura.io/v3/XXXX
      - key: REGISTRY_ADDR
        value: # 0x...
      - key: IPFS_HTTP_GATEWAY
        value: https://ipfs.io/ipfs/
      - key: GATEWAY_NAME
        value: gic-gateway
      - key: GATEWAY_HMAC_SECRET
        generateValue: true

  - type: web
    name: oaa-hub
    env: node
    rootDir: companion_site_starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    plan: starter
    autoDeploy: true
    envVars:
      - key: GIC_RPC_URL
        fromService:
          type: web
          name: gic-gateway
          envVarKey: RPC_URL    # optional; override with your own
      - key: GIC_REGISTRY_ADDR
        value: # 0x...
      - key: GIC_GATEWAY_BASE_URL
        fromService:
          type: web
          name: gic-gateway
          property: url
      - key: GATEWAY_HMAC_SECRET
        fromService:
          type: web
          name: gic-gateway
          envVarKey: GATEWAY_HMAC_SECRET
      - key: LEDGER_BASE_URL
        value: # https://ledger.yourdomain/api
      - key: LEDGER_ADMIN_TOKEN
        generateValue: true
      - key: IPFS_PIN_ENDPOINT
        value: https://api.web3.storage/upload
      - key: IPFS_PIN_TOKEN
        sync: false  # set in dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: civic-redis
          property: connectionString
      - key: GIC_COMPANION_LABELS
        value: jade,zeus,eve,hermes
      - key: GIC_REGISTRAR_PRIVATE_KEY
        sync: false  # set in dashboard

  - type: worker
    name: oaa-publish-worker
    env: node
    rootDir: companion_site_starter
    buildCommand: npm ci
    startCommand: node -r esbuild-register workers/publishWorker.ts
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: civic-redis
          property: connectionString
      - key: QUEUE_PUBLISH_CONCURRENCY
        value: "5"
      - key: GIC_RPC_URL
        value: # same as hub
      - key: GIC_REGISTRY_ADDR
        value: # 0x...
      - key: GIC_REGISTRAR_PRIVATE_KEY
        sync: false
      - key: GIC_GATEWAY_BASE_URL
        fromService:
          type: web
          name: gic-gateway
          property: url
      - key: GATEWAY_HMAC_SECRET
        fromService:
          type: web
          name: gic-gateway
          envVarKey: GATEWAY_HMAC_SECRET

  - type: redis
    name: civic-redis
    ipAllowList: []   # private
    plan: starter