name: eomm-sync
on:
  schedule:
    - cron: "*/30 * * * *"    # every 30 minutes
  workflow_dispatch: {}        # run on-demand

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      LEDGER_BASE_URL: ${{ vars.LEDGER_BASE_URL }}
      LEDGER_ADMIN_TOKEN: ${{ secrets.LEDGER_ADMIN_TOKEN }}
      # Optional: EOMM_DIR: "data/eomm"
      DRY_RUN: "false"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: E.O.M.M. → Ledger sync (with quarantine)
        run: node scripts/eomm-sync.mjs

      - name: Summarize quarantine
        run: |
          if [ -f data/eomm/_invalid/SUMMARY.json ]; then
            echo "### EOMM Quarantine" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            cat data/eomm/_invalid/SUMMARY.json >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "### EOMM Quarantine\nNo invalid files." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload quarantine summary (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eomm-quarantine
          path: data/eomm/_invalid/SUMMARY.json
          if-no-files-found: ignore